### ISSUE TITLE
Returning null array

### ISSUE THREAD

**Issue by alskenobi** [mapbox/earcut#101]
Hello,
I'm trying to get the result with this values:
`console.log(earcut([1, 5, 15, 1, 5, 13, -1, 5, 13, -1, 5, 15, -5, 5, 15, 5, 5, 5, 5, 5, 15], null, 3))`

Am I doing something wrong?
Even "closing" the polygon with the first point, it still not working.

This is working if I remove the "Y" axis and using simple 2D.

Thanks sou much for this library!

**Comment by mourner** [comment]
I think it's because the example above is degenerate — all the points have the same y (5), so it's basically a single line.

**Comment by mourner** [comment]
To add to that, Earcut only triangulates in XY plane, disregarding Z completely. See #21 for more discussion.

**Comment by alskenobi** [comment]
In this example
```
[ 1,
  5,
  15,
  1,
  4,
  15,
  -1,
  4,
  15,
  -1,
  4.4,
  15,
  -1,
  5,
  15,
  -5,
  5,
  15,
  -5,
  -5,
  15,
  5,
  5,
  15 ]
```
The "Z" axis is not changing, and I have a result.
Is it necessary that "X" or "Y" changes?

**Comment by mourner** [comment]
Yes, because Earcut triangulates as if the shape was projected on an XY plane. See #21.

**Comment by alskenobi** [comment]
Ok, thank you.
I'll validate that before to send to the Method.
Thanks!
