### ISSUE TITLE
Triangulating fonts with holes?

### ISSUE THREAD

**Issue by samsonsite1** [mapbox/earcut#104]
Hello,
I'm trying to triangulate some Japanese fonts, however I've encountered some issues with holes.

One particular character has 4 holes, but it doesn't triangulate correctly.
This one, Unicode escape sequence:
"\u7530"

I have one question about holes.  Should the last point be repeated to indicate a closed `shape?`
I tried removing any duplicate end points, but the result is not correct either.

Code:

 ```
using Coord = double;
 using N = uint32_t;
 using Point = std::array<Coord, 2>;

 std::vector<std::vector<Point>> polygon;

 // outer points
 polygon.push_back( {{25, 0}, {17, 0}, {17, 2}, {-17, 2}, {-17, 0}, {-25, 0}, {-25, 48}, {25, 48}, {25, 0}} );

 // 4 holes
 polygon.push_back( {{-3, 23}, {-17, 23}, {-17, 8}, {-3, 8}, {-3, 23}} );
 polygon.push_back( {{-3, 29}, {-3, 42}, {-17, 42}, {-17, 29}, {-3, 29}} );
 polygon.push_back( {{4, 42}, {4, 29}, {17, 29}, {17, 42}, {4, 42}} );
 polygon.push_back( {{17, 8}, {17, 23}, {4, 23}, {4, 8}, {17, 8}} );

 std::vector<N> trig_indices = mapbox::earcut<N>(polygon);
```
what it should look like:
![font](https://user-images.githubusercontent.com/7414478/45256945-6e793d00-b38d-11e8-936b-6e3f0d1c9329.PNG)

**Comment by mrgreywater** [comment]
Looking at the code, this question is probably meant to be posted to [earcut.hpp](https://github.com/mapbox/earcut.hpp/issues).

I don't see the issue with your example. It's triangulated like this with earcut.hpp: 
![image](https://user-images.githubusercontent.com/2902403/45257171-008b4080-b3a2-11e8-934d-cf2ee24d8af4.png)

> Should the last point be repeated to indicate a closed shape?

Both is valid, the duplicate point would be ignored.

**Comment by samsonsite1** [comment]
Thanks, I have another question about holes.
Does the winding order of holes matter, when sending it to mapbox::earcut ?
Should they use the same winding order of the outer points, or should they be opposite to them?

The holes listed above are given a winding order that is opposite to the outer points.
Not sure where my error lies.

**Comment by samsonsite1** [comment]
My attempt:

![result](https://user-images.githubusercontent.com/7414478/45257779-4b558a00-b39b-11e8-8270-d909febe401c.PNG)

```
Indices returned:

num_trigs: 26

[ 0] trig:   5,  17,  16
[ 1] trig:  20,  23,  15
[ 2] trig:   5,  11,  10
[ 3] trig:  13,  12,  27
[ 4] trig:   5,   4,   3
[ 5] trig:   2,   1,   8
[ 6] trig:   6,   5,  16
[ 7] trig:  20,  15,  18
[ 8] trig:  17,   5,  10
[ 9] trig:  13,  27,  26
[10] trig:  11,   5,   3
[11] trig:   2,   8,   7
[12] trig:   7,   6,  16
[13] trig:  18,  17,  10
[14] trig:  28,  11,   3
[15] trig:   7,  16,  22
[16] trig:  20,  18,  10
[17] trig:  28,   3,   2
[18] trig:   7,  22,  21
[19] trig:  21,  20,  10
[20] trig:  28,   2,   7
[21] trig:  21,  10,  13
[22] trig:  25,  28,   7
[23] trig:  21,  13,  26
[24] trig:  25,   7,  21
[25] trig:  21,  26,  25
max_index: 28
```

**Comment by mrgreywater** [comment]
The usage paragraph of earcut.hpp clarifies that "Any winding order works". Therefore the winding order of the input of earcut.hpp doesn't change it's result. Neither of the outer points, nor the holes. The result are clockwise triangles given with indices.

Your indices appear correct, your rendering doesn't. You can check the [visualization program](https://github.com/mapbox/earcut.hpp/blob/master/test/viz.cpp) for an example implementation for drawing your polygon.

**Comment by samsonsite1** [comment]
Thank you very much!  I found my problem.  The points loaded from file were in a different order than
the points I used for rendering.  Thanks again.
