### ISSUE TITLE
Can't trianglate my data

### ISSUE THREAD

**Issue by wemamawe** [mapbox/earcut#106]
herer is my point array, it has 4 points with 3 dimension. `[6.992614615126513, 9.283462616614997, 0, 6.992614615126513, 9.283462616614997, 3.9078439025711305, 0, 0, 3.9078439025711305, 0, 0, 0]`
it is a rectangle, but when i used earcut to trianglate this and returns a empty result.

**Comment by mourner** [comment]
See #21 for discussion on why this happens.
