### ISSUE TITLE
function intersections() confusing, possibly incorrect

### ISSUE THREAD

**Issue by donbright** [mapbox/earcut#110]
hello, i had some troubles understanding this code

```
// check if two segments intersect
function intersects(p1, q1, p2, q2) {
    if ((equals(p1, q1) && equals(p2, q2)) ||
        (equals(p1, q2) && equals(p2, q1))) return true;
    return area(p1, q1, p2) > 0 !== area(p1, q1, q2) > 0 &&
           area(p2, q2, p1) > 0 !== area(p2, q2, q1) > 0;
}
```

the intersection algorithm appears to be based on checking the winding (orientation) (side) of points in relation to each other, like on this website: https://www.geeksforgeeks.org/check-if-two-given-line-segments-intersect/

however that algorithm presumes the segments are p1-q1  and p2-q2

my problem is in the beginning, which appears to be a check for whether the two segments have the same endpoints.

```
    if ((equals(p1, q1) && equals(p2, q2)) ||
        (equals(p1, q2) && equals(p2, q1))) return true;

```

now, it appears to me that if the segments are p1-q1 and p2-q2 then the first line of this code is checking whether p1-q1 is a "point", not a line segment, since if p1==q1 then the segment p1-q1 would have 0 length. 

the second line of code seems to be checking of p1-q1 lies on the endpoints of q2-p2, which seems to be checking something different than the first line of code. 

Example:

Here we have two segments, p1-q1 and p2-q2, now, the function returns opposite results depending on when you swap p2 with q2, even though that shouldnt make a difference in an intersection algorithm. 

`
   p1=0,0.  q1=1,1.  p2=0,0.  q2=1,1

    if ((equals(p1, q1) && equals(p2, q2)) ||  
        (equals(p1, q2) && equals(p2, q1))) return true;

    (false && false || false and false) -> result is false

----

   p1=0,0.  q1=1,1.  p2=1,1.  q2=0,0

    if ((equals(p1, q1) && equals(p2, q2)) ||  
        (equals(p1, q2) && equals(p2, q1))) return true;

    false && false || true && true.    -> result is true

`

i am not sure if i am missing something, but if anyone could help me understand i would appreciate. thank you.

**Comment by mrgreywater** [comment]
The segments are probably p1-p2 and q1-q2.

**Comment by donbright** [comment]
it also seems a bit ambivalent on the question of whether the endpoint of one segment is exactly on the body of the other segment. 

if that is true then the area will be 0, but this code is checking for >0 always, never for the case of 0 itself. 

for example , lets look at how we get two different answers for the same pair of line segments, depending on which order the data is given to the function.

```
p1 =0,0. q1 = 1,1.      p2 = 0.5, 0.5,   q2 = 1,0

lets calculate this test:    (area(p1, q1, p2) > 0) != (area(p1, q1, q2) > 0) &&
           (area(p2, q2, p1) > 0) != (area(p2, q2, q1) > 0);

   area of p1 q1 p2 will be 0.   area of p1 q1 q2 will be clockwise.
    area of p2 q2 p1 will be clockwise, area of p2 q2 q1 will be counterclockwise

 result of test is   (false != true) && (true != false), total result is 'true'

----

now what if we swap p1 with q1? same line segment, ... does it give same result?

p1 =1,1. q1 = 0,0.      p2 = 0.5, 0.5,   q2 = 1,0

lets calculate this test:    (area(p1, q1, p2) > 0) != (area(p1, q1, q2) > 0) &&
           (area(p2, q2, p1) > 0) != (area(p2, q2, q1) > 0);

   area of p1 q1 p2 will be 0.   area of p1 q1 q2 will be counterclockwise.
    area of p2 q2 p1 will be counterclockwise, area of p2 q2 q1 will be clockwise

 result of test is   (false != false) && (false != true), total result is 'false'
  
----

in this example above we see that swapping p1 and q1 (which are endpoints of a line segment) produces a different answer for 'intersects()' code as given. 

(counterclockwise is also called anticlockwise , and is typically "less than 0", although my example would demonstrate the same underlying issue if you considered it backwards)
 
```

it seems to me like intersects() might work better if it operated the same regardless of order of the two line segments fed into it. 



thanks

**Comment by mourner** [comment]
@donbright thanks a lot for the valuable input — [intersects routine](https://github.com/mapbox/earcut/blob/master/src/earcut.js#L493-L508) should now be correct.
