### ISSUE TITLE
No result from earcut

### ISSUE THREAD

**Issue by mmaenz** [mapbox/earcut#128]
Hi,

I don't get any result with these values:  
triangles = earcut([10, -10, -10, 10, 10, -10, 10, 10, 10, 10, -10, 10], null, 3);

I would expect an array with 6 values. Am I doing something wrong?

Here I compared your working sample earcut([10,0,1, 0,50,2, 60,60,3, 70,10,4], null, 3) in 3d with my points:
![image](https://user-images.githubusercontent.com/22559887/67009140-3e9d7c80-f0eb-11e9-80dc-fcc65d0c4d63.png)

Any idea what's going on?

**Comment by johncalvinyoung** [comment]
Earcut accepts 3D vectors but triangulates them in 2D--ignoring the 3rd dimension. your four points collapse to two and hit the redundancy check, which is why they aren't being triangulated.

**Comment by mourner** [comment]
Yep. More discussion at #21
