### ISSUE TITLE
Another degenerate case causing bad triangulation

### ISSUE THREAD

**Issue by mourner** [mapbox/earcut#131]
Taken from https://github.com/mapbox/mapbox-gl-js/issues/9085:

```
[
[[3506,-2048],[7464,402],[-2048,2685],[-2048,-2048],[3506,-2048]],
[[-2048,-37],[1235,747],[338,-1464],[-116,-1188],[-2048,-381],[-2048,-37]],
[[-1491,-1981],[-1300,-1800],[-1155,-1981],[-1491,-1981]]
]
```

![image](https://user-images.githubusercontent.com/25395/71728233-311fa500-2e45-11ea-9299-ddc3da8a69b1.png)

**Comment by Eh2406** [comment]
Thanks for the fix!!! Let me know when ( and how ) it is convenient for use to confer that this all the things that we are seeing.
