### ISSUE TITLE
How to triangulate 8-shaped polygon?

### ISSUE THREAD

**Issue by tab1887** [mapbox/earcut#134]
Hi,

first of all many thanks for providing this great tool.
I'm trying to use it in a Unity project to create a  mesh from a user created path. 

One of my test cases has a path in the shape of a hand-written digit "8". This is unfortunately not triangulated as I would intuitively expect it, and as it is working in your hourglass test case. 

Given the points
[[[0,2],[1,1],[2,2],[3,3],[4,2],[3,1],[2,2],[1,3]]]
I get 
![image](https://user-images.githubusercontent.com/40249029/74114688-c6802880-4bab-11ea-8b57-357510964b64.png)

Or, alternatively without a vertex at the intersection point
[[[0,2],[1,1],[3,3],[4,2],[3,1],[1,3]]]

![image](https://user-images.githubusercontent.com/40249029/74114716-e9124180-4bab-11ea-8899-da728f6676ed.png)

In contrast the hourglass is working as expected:
[[[7,18],[7,15],[5,15],[7,13],[7,15],[17,17]]]
![image](https://user-images.githubusercontent.com/40249029/74114938-05fb4480-4bad-11ea-97be-a9b40d880305.png)

Could you please let me know if there is anything I can do to get the two squares (or in the real world n-gons) filled?
Maybe some kind of pre-processing of the vertex list?

Kind Regards,
Tim

**Comment by mrgreywater** [comment]
Earcut works on simple polygons. It's not supposed to fix self intersections. It actually can't even in the first case, because earcut only returns an index buffer, and the intersection point isn't in your vertex list.

You can simplify your polygon (clear self intersections) with a library like clipper: https://github.com/junmer/clipper-lib

**Comment by tab1887** [comment]
Many thanks for the fast reply and for pointing me to clipper. I will definitely have a look at it.

I just asked because your readme explicitly mentions self intersections and other examples work just fine. Anyway, thank you very much for your help.
