### ISSUE TITLE
[QUESTION] Finding neighbour triangles after triangulation process

### ISSUE THREAD

**Issue by xDGameStudios** [mapbox/earcut#137]
Hi everyone..
this library is incredible and fits the purpose I'm looking for :)
but after triangulating the polygon I wanted to make an adjacency matrix regarding vertices and triangles. The adjacency matrix for vertices was actually quite simple to do...
just created a square grid with data.length size. then loop for all the triangles and marked all the vertices in that triangle as adjacent (true in the grid). after looping for all vertices I got the adjacency matrix for vertices. Now for the triangles I'm really stuck if you could give me some guidance maybe pseudo-code steps.. :) thank you a lot!

**Comment by mourner** [comment]
Sorry for a late response — I don't know the answer. Perhaps making a similar adjacency matrix for triangles, and then making two triangles adjacent if they have 2 vertices in common?
