### ISSUE TITLE
earcut ported to JAVA

### ISSUE THREAD

**Issue by andresoviedo** [mapbox/earcut#138]
Dear team,

Thank you very much for sharing your awesome earcut library.
I have ported your latest javascript implementation to JAVA language.

https://github.com/the3deers/earcut-java

I just wanted to let you know, in case you want to own it or link it in the README.md.
I have commited the code under the MIT License.

Kind regards

**Comment by mourner** [comment]
Thank you! Feel free to submit a PR that adds it to the list of ports in the readme.
