### ISSUE TITLE
Bug with vertical object in 3dim space

### ISSUE THREAD

**Issue by jolegat** [mapbox/earcut#150]
Hello,

thanks for earcut! It helps me a lot!

Unfortunately I came across a problem using it in a 3dim space: earcut() returns an empty array for precisely vertical objects. 

It is easily reproducable, e.g.:
earcut ([1,1,0,  2,1,0,  2,1,1,  1,1,1], 0, 3) -> []

If I switch y and z coords it works:
earcut ([1,0,1,  2,0,1,  2,1,1,  1,1,1], 0, 3) -> [2, 3, 0, 0, 1, 2]

Cheers
jo

**Comment by mourner** [comment]
It's not a bug, it's a design limitation — `earcut` only triangulates the XY projection in 2D plane and passes Z as is. See #21 for the discussion.
