### ISSUE TITLE
Failure with simple case in 3D

### ISSUE THREAD

**Issue by PieroV** [mapbox/earcut#153]
Hi, this library seems very interesting! However I was trying it out with some simple cases to get started, but I encountered an unexpected result:

```node
> earcut([0, 0, 0,  1, 0, 0,  1, 1, 0,  0, 1, 0], null, 3)
[ 2, 3, 0, 0, 1, 2 ]
> earcut([0, 0, 0,  0, 1, 0,  0, 1, 1,  0, 0, 1], null, 3)
[]
```

As you can see, I performed a simple permutation: X -> Y, Y -> Z, Z -> X, so I expected the same result.

For my use case, I am sure all my vertices are planar, so I can project them and run the tessellation in 2D instead, but I thought of reporting this problem anyway.

Thanks 🌝 !

**Comment by mourner** [comment]
This is by design. See #21 for discussion along with many linked issues.

**Comment by PieroV** [comment]
I see. Thanks for your answer. Could you please consider adding this in the readme, with the 3D example?
