### ISSUE TITLE
Does the triangulation consider only 2 dimensions?

### ISSUE THREAD

**Issue by liu-hanli** [mapbox/earcut#165]
I'm using the version `2.2.4`.

When the data has 3 dimensions, and the face is parallel to the 3rd axis, the indexing array will be empty.

```js
const earcut = require('earcut');

const data = [
  [
    [0, 0, 0],
    [1, 0, 0],
    [1, 0, 1],
    [0, 0, 1],
  ]
];

const { vertices, holes, dimensions } = earcut.flatten(data);
const indices = earcut.default(vertices, holes, dimensions);
console.log(indices);
```

output: `[]`

**Comment by mourner** [comment]
Yes. There's a note in the readme:

> Note that Earcut is a 2D triangulation algorithm, and handles 3D data as if it was projected onto the XY plane (with Z component ignored).
