### ISSUE TITLE
How do I use a polygon with Steiner points

### ISSUE THREAD

**Issue by fbkolik1907** [mapbox/earcut#166]
I have a large polygon array, then I calculate steiner points in this polygon and I want to use it. How can I use it? I need code as an example. I can do this using the cdt2d library but it is very slow. Hovewer I couldn't do it in earcut. It is said that steiner point support is in earcut, how can I use it?

For example, there is such a polygon [0, 0, 100, 0, 100, 100, 100, 0, 100, 20, 20, 80, 20, 80, 80, 80, 20, 80].  I want the points from 20, 20 to be steiner points and not holes, how can I use it?

**Comment by mourner** [comment]
You would supply a hole index for each of those points, e.g.: 

```js
earcut([
  0, 0, // 0
  100, 0, // 1
  100, 100, // 2
  100, 0, // 3
  0, 0, // 4
  20, 20, // 5
  80, 20, // 6
  80, 80, // 7
  20, 80 // 8
], [5, 6, 7, 8])

**Comment by fbkolik1907** [comment]
thanks a lot

Volodymyr Agafonkin ***@***.***>, 14 Şub 2024 Çar, 13:08
tarihinde şunu yazdı:
