### ISSUE TITLE
Provide appropriate full examples

### ISSUE THREAD

**Issue by eslachance** [mapbox/earcut#167]
2.1k stars, 16 contributors on this project and not a single one of you has ever had the time to write an example showing how to use/import in a node project, or how to properly import the library in a module script.

Don't assume that people inherently know how to use libraries where you only have `npm install` or links to the CDN - a lot of beginners want to use your stuff and do not have this pre-requisite information. It doesn't take much to write proper examples in a readme. Please do that!

**Comment by mourner** [comment]
I get your criticism, but I don't understand why you have to be so condescending in an issue report. Please be kind. This is free and open source. Maintainers are people with feelings too.

**Comment by Zxilly** [comment]
You should look for a tutorial and then learn some of the basics, rather than expecting to see a start-from-scratch guide for every dependency library you use.

**Comment by lorenzoMezza** [comment]
you are right.unfortunately javascript libraries, without guidance on how to use them, are often very complex, given the nature of the javascipt language where anything can mean anything.
