### ISSUE TITLE
Incorrect triangulation with a shape in a hole

### ISSUE THREAD

**Issue by jnromero** [mapbox/earcut#168]
I am trying to triangulate a shape with a hole with a smaller shape inside the hole.  I am not sure if this is supported in earcut.

```
const x1=-1.741999999999999;
const x2=-1.7419999999999989;

const vertices=[
    // outer square
    -9.202,-13.68,
    -9.202,-32.33,
    9.4480,-32.33,
    9.4480,-13.68,

    // cut out inner square
    5.7180,-17.41,
    5.7180,-28.6,
    -5.472,-28.6,
    -5.472,-17.41,

    // smaller interior square
    x1,-21.14,
    x2,-24.87,
    1.988,-24.87,
    1.988,-21.14
]

const holeIndices = [4,8];

const triangles = earcut(vertices, holeIndices);

```
It appears that as long as x2<x1, no matter how small the difference, then the triangulation is incorrect giving triangles.length=24.  Otherwise, if x2>=x1, then the triangulation is correct giving triangles.length=30.  

Here is the example: https://jsfiddle.net/7c2bpgv3/

On further investigation, it appears that the triangulation still isn't correct with x2>=x1, giving something like this:

![triangles](https://github.com/mapbox/earcut/assets/8127592/cd51269c-8084-47f8-bfbf-f3635b1097f2)

**Comment by mrgreywater** [comment]
Earcut does not support nested shapes like this. You'd have to triangulate the outer polygon with the hole in one call, and then the inner polygon.
