### ISSUE TITLE
Triangulation result is different from expectation

### ISSUE THREAD

**Issue by pockie** [mapbox/earcut#170]
I have the following rectangle with an inner point which I add as a hole described in #166. In the first picture you see the result. But I expected the triangulation from the second image. My questions are: Is the result from earcut correct? Is there a way to get my expected result?

```javascript
earcut([
  0, 0, // 0
  3000, 0, // 1
  3000, 2400, // 2
  0, 2400, // 3
  0, 0, // 4
  986, 1210, // 5
], [5])
```

![image](https://github.com/mapbox/earcut/assets/7887953/d537e373-2b43-4ce7-ad85-c0328a71718a)
![image](https://github.com/mapbox/earcut/assets/7887953/42837874-06aa-4daa-b609-f4f3912a997a)

**Comment by mourner** [comment]
The result is expected and correct — the triangles cover and match the original shape exactly, and Earcut doesn't give any additional guarantees on triangulation shape. You might be looking for Constrained Delaunay Triangulation, which guarantees somewhat well-formed triangles, but there is no fast and robust JS library for performing such triangulation.

**Comment by pockie** [comment]
Thanks for the fast reply. poly2tri.js works for me to solve this problem.
