### ISSUE TITLE
Eracut gives an empty result

### ISSUE THREAD

**Issue by Priyank30** [mapbox/earcut#25]
Coords: [10, 10, 610, 10, 610, 610, 10, 610]
HoleIndices: [50, 50, 150, 50, 150, 150, 50, 150]
numDimensions: 2

Eracut is returning an empty result for the above data set and both are rectangle vertices.

**Comment by mourner** [comment]
That input doesn't look valid. You have only 4 vertices, and hole indices should contain indices rather than vertice coordinates. Read more in the docs: https://github.com/mapbox/earcut#usage

**Comment by Priyank30** [comment]
@mourner 
You are right that's my fault. Would you tell me if I have a vertices of erasing shape how could I get indices? I just need a way rest I will try to figure out my self.

**Comment by mourner** [comment]
In your case it would look like this:

```
coords: [10, 10, 610, 10, 610, 610, 10, 610, 50, 50, 150, 50, 150, 150, 50, 150]
holeIndices: [4] // one hole, starts at index 4 in coords array
```

**Comment by Priyank30** [comment]
Thanks @mourner.
 With your help I have generated graphics object with hole in [pixijs](https://github.com/GoodBoyDigital/pixi.js/issues/1755) library.
