### ISSUE TITLE
Comparison between earcut and libtess.

### ISSUE THREAD

**Issue by NewCompte** [mapbox/earcut#27]
Not sure this fits here, but I wanted to say this.

I tried to use this library to cut my maps' walls into convex pieces for box2d. I thought the fact that all my point were on a grid would make this library perform correctly. It ended up being wrong on some maps:

earcut: http://i.imgur.com/F4aC3S2.png
libtess: http://i.imgur.com/PZ41Gkf.png

**Comment by mourner** [comment]
Sorry for a late reply — can you share the test data that caused the wrong results? Does it contain self-intersections?
