### ISSUE TITLE
Less than expected number of triangles?

### ISSUE THREAD

**Issue by iominh** [mapbox/earcut#28]
Hi,

First, thanks for creating this amazing library and open sourcing it! I've enjoyed using it but I'm having  trouble understanding the following results:

```javascript
 earcut([-180, -90, -180, 0, -180, 90, -90, -90, -90, 0, -90, 90, 0, -90, 0, 0, 0, 90, 90, -90, 90, 0, 90, 90, 180, -90, 180, 0, 180, 90]);
```

The result I get back is 4 triangles but shouldn't there be 8 triangles since there are no holes? 
```javascript
[3, 2, 0, 12, 11, 9, 9, 8, 6, 6, 5, 3]
```

Taking a step back, I'm working on partitioning the globe with 15 points (lon, lat) to visualize on a map but the problem is that when I render these triangles, I'm left with 4 triangle holes when I'm not expecting any?

**Comment by minhongrails** [comment]
Actually, I think I just gave it bad input (the vertices weren't continuous), so here's a better input:

```javascript
earcut([-180,-90,-180,0,-180,90,-90,90,-90,0,-90,-90,0,-90,0,0,0,90,90,90,90,0,90,-90,180,-90,180,0,180,90]);
```

Unfortunately I'm still getting only 4 triangles instead of the expected 8. The 15 points should be a continuous polygon around the globe but I probably need to figure out an alternative set of input points.

```javascript
3,2,0,11,9,8,5,3,0,11,8,6
```

Earcut works great whenever I simplify the problem to earcut([-180,-90, -180,90, 180,90, 180,-90]), which returns the expected 2 triangles. Unfortunately, for whatever reason I need to provide intermediate points in CesiumJS (the map/globe that I'm using) or else it doesn't seem to render the triangles properly.

**Comment by minhongrails** [comment]
Sorry for the comment spam :). I thought I'll take a step back to explain my use case, provide simpler examples, and show some illustrations. I'm trying to color everything outside of an arbitrary polygon on a CesiumJS map. 

I start by creating triangle polygons that cover the globe (the triangles are covered differently just for illustration purposes):
![p1](https://cloud.githubusercontent.com/assets/1434477/8018144/73147a7c-0bda-11e5-95a3-e5e962c3bd71.jpg)

Here's a photo of an example rectangle hole:
![p0](https://cloud.githubusercontent.com/assets/1434477/8018152/ad23d99c-0bda-11e5-8572-4cd990e62182.jpg)

Next, I remove the intersecting triangles with the hole:
![p2](https://cloud.githubusercontent.com/assets/1434477/8018175/bb45527a-0bdb-11e5-8882-7821bcf7c729.jpg)

Finally, I use earcut to draw triangles that don't intersect the hole:
![p3](https://cloud.githubusercontent.com/assets/1434477/8018179/d5e1a26e-0bdb-11e5-8fb8-53ad5f57405b.jpg)

Unfortunately, for some reason it seems that in this scenario the triangles seem to cover the hole when I was hoping they would leave the hole remaining. 

Here's some of the results I get back from earcut

```javascript
# Triangle: [-135, 0, -135, 45, -90, 45]
# Holes: [-97, 31, -97, 39, -87, 39, -87, 31]
earcut([-135,0,  -135, 45,  -90,45,  -97,31,  -97,39, -87,39,  -87,31]
# result: [4, 0, 2, 1, 0, 3, 6, 3, 0, 4, 2, 1, 1, 3, 6, 4, 1, 6, 5, 4, 6]
# the 5 returned triangles look like
# triangle1: 4,0,2 = [-97, 39], [-135, 0], [-90, 45]
# triangle2: 1,0,3 = [-135, 45], [-135, 0], [-97, 31]
# ...
```

**Comment by minhongrails** [comment]
As an update, I switched to libtess, which appears to work for the above example.

Here's the triangulation around the hole:

![libtess_success](https://cloud.githubusercontent.com/assets/1434477/8022595/acaab0a6-0ca9-11e5-98bb-035049dafda5.png)

Here's how it looks (this was my intended goal):

![end_result](https://cloud.githubusercontent.com/assets/1434477/8022596/b898a45e-0ca9-11e5-91ed-4999cb70b667.png)

**Comment by mourner** [comment]
Ah sorry, I somehow missed this issue — looking into your samples now.

**Comment by mourner** [comment]
OK so I tried to understand your input and here's how both test cases look like and how they'd be interpreted by Earcut:

![2015-07-07 14 12 10](https://cloud.githubusercontent.com/assets/25395/8544957/799b2d96-24b2-11e5-8a00-122135be8e7b.jpg)

Obviously these are not valid polygons, and Earcut doesn't support self-intersections like this, so it is pretty much expected to produce invalid results.
