### ISSUE TITLE
Expose earcutArea function

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/earcut#53]
For tile providers, it helps to do the same comparison between geometry area and earcut area that is done in [earcut's tests](https://github.com/mapbox/earcut/blob/master/test/test.js#L52-L85), which helps ensure that the tiles are 100% compatible with earcut's algorithm. Would it be possible to expose this calculation as a helper method, like `earcutArea(geom)` that returns the sum of the areas of the earcut triangles? Having it exposed would reduce the likelihood of area miscalculation in tile provider tests, and would prevent the tests from getting out of sync.

cc/ @mapsam @mourner @springmeyer

**Comment by mourner** [comment]
Maybe something like this?

```js
var triangles = earcut(vertices, holeIndices);
var deviation = earcut.deviation(triangles, vertices); 
// returns abs(sum of triangle areas /  polygon area - 1)
```

**Comment by jakepruitt** [comment]
@mourner :grinning:! That would be wonderful.

**Comment by springmeyer** [comment]
\o/
