### ISSUE TITLE
Bower Package

### ISSUE THREAD

**Issue by chopper** [mapbox/earcut#55]
Awesome library. It would be fantastic to make this available as a bower package, too. Any plans for this?

**Comment by tmcw** [comment]
Nope, feel free to use this package from npm, webpack, [npmcdn](https://npmcdn.com/), downloading a standalone file, and all other forms of inclusion. We do not support or recommend bower.

**Comment by chopper** [comment]
Shame - thanks for the quick reply.

**Comment by chopper** [comment]
@tmcw—out of curiosity: why is that?

**Comment by tmcw** [comment]
- Bower is effectively [not developed anymore](https://github.com/bower/bower/pull/1748#issuecomment-150104311)
- It is a pain to support for library maintainers (e.g. requires committing build artifacts to the repo, which is a very bad practice), and this time is better spent improving the library itself (see https://github.com/rackt/redux/issues/944 for a sample discussion why)
- It is effectively superceded by the NPM registry and awesome tools like Browserify, Webpack and JSPM

---

Bower is an abandoned tool that's inconvenient for maintainers and worse than npm, webpack, jspm, and other systems.

**Comment by chopper** [comment]
Interesting—it's been working fine for our purposes, but I can see you rationale :) I got it to work using npm and browserify and will explore using this setup more in the future. Thanks!

**Comment by Wilt** [comment]
You can use this line to make it work for bower:

    "earcut": "https://github.com/mapbox/earcut.git",
