### ISSUE TITLE
error in findHoleBridge

### ISSUE THREAD

**Issue by LFWill** [mapbox/earcut#60]
I'm getting an error in the function findHoleBridge() on this line:
297:        if (hy <= p.y && hy >= p.next.y) {

p is null. 

I've been working on this for a few hours and I haven't made any headway. I'm using 3-dimensional polygons with several holes. What might cause this problem?

**Comment by tmcw** [comment]
> I'm using 3-dimensional polygons with several holes.

That's the problem: 3D polygons are not supported, as mentioned in https://github.com/mapbox/earcut/issues/21

**Comment by mourner** [comment]
@LFWill sorry, just discovered this issue — could you provide a minimal test case? 3D polygons are supported in a sense that they're triangulated as projected on a XY plane, but they shouldn't produce an error like the above.

**Comment by LFWill** [comment]
I no longer have the code that was producing the above error. To solve my problem I projected to 2D using the "greatest area" method you described in #21

**Comment by mourner** [comment]
Wonderful, thanks! Feel free to open a new issue if you ever stumble upon the error above.
