### ISSUE TITLE
Show error 'Uncaught ReferenceError: module is not defined   earcut.js:3'

### ISSUE THREAD

**Issue by kkotaro0111** [mapbox/earcut#61]
Currentry:
```
module.exports = earcut;
```

Better:
```
if( typeof module !== 'undefined' && typeof module.exports !== 'undefined'){
  module.exports = earcut;
}
```

**Comment by jfirebaugh** [comment]
This module is provided with a CommonJS interface. If you want to use it in the browser, you'll need to package it using browserify or webpack.

**Comment by jfirebaugh** [comment]
Also there are browser builds on npmcdn, see https://github.com/mapbox/earcut#install.
