### ISSUE TITLE
Question: What's the quickest way to find neighbours of a given triangle

### ISSUE THREAD

**Issue by liebrand** [mapbox/earcut#63]
Hi there,

I understand earcut produces the triangles in cw winding order (I saw the thread to get ccw). However, obviously given the original geojson, the winding order doesn't guarantee the position of neighbouring triangles within the array (or am I mistaken? I'm thinking about cases where some triangles have only one or two neighbours vs three...)

What would be the quickest way to find the neighbouring triangles of a given triangle in the results array? short of obviously linearly running through the entire results...

**Comment by liebrand** [comment]
(oh and as a side question: for a given point inside the original geometry, what would you recommend as the fastest way to find the triangle containing it? I was going to use rbush with bounding rects for each triangle, and then just compare the two (or three) triangles it ought to find; or is there a better/faster way?)

**Comment by mourner** [comment]
I'm not sure — in theory, some Delaunay triangulation algorithms produce a point location data structure where you can find a triangle from point very fast. However I'm not aware of fast JS implementations. To do such queries with Earcut results, you would have to use some kind of index like RBush, but I don't know how fast this will be.
