### ISSUE TITLE
Broken triangulation

### ISSUE THREAD

**Issue by cybafelo** [mapbox/earcut#68]
Hey - I'm sorry I don't know if this package is still maintained - I have a 3d quad with the following vertices:

[
2.456295967102051,
1.5326589345932007,
0.5580052137374878,
2.3840434551239014,
1.6075363159179688,
0.5736544132232666,
2.3840434551239014,
1.6075363159179688,
0.4867267608642578,
2.456295967102051,
1.5326589345932007,
0.471077561378479
]

and many more such quads - ex.

[
2.8560659885406494,
0.7904728651046753,
0.4427383840084076,
2.8363993167877197,
0.8773361444473267,
0.45491600036621094,
2.8363993167877197,
0.8773361444473267,
0.36798834800720215,
2.8560659885406494,
0.7904728651046753,
0.3558107316493988
]

And earcut is returning an empty array after executing earcut(vertices, null, 3)

Some quads (non co-planar quads) it is returning at least one triangle - and I can correct this by adding the missing vertice to a triangle sharing an edge and all is fine - but I cannot solve the case where earcut is returning nothing - i would have to do the triangulation manually.

I really need to get this to work - or can someone point me to a triangulation library which works the same as earcut? It doesn't have to be fast at all - just produce a triangle list of 3d coordinates from a list of vertices - exactly the way earcut does it - i tried plntri but the examples are poor and cannot figure out a way to call the function for 3d coordinates - libtess seems super complicated i have no idea how to get it working - the example webpage is terribly confusing and not documented at all.

any help would be MUCH MUCH appreciated..

**Comment by jfirebaugh** [comment]
Earcut does not support 3d tessellation -- you will need to project your shapes into 2d first. See previous discussions in #21, #43.

**Comment by cybafelo** [comment]
Hey - thanks for the reply..

I did some additional work trying to solve the problem - and discovered the following:

I'm taking the first three points and calculating the normal - I'm doing this because I want to project the fourth vertice onto the same plane as the first three - so that I can eliminate the 3D space and triangulate essentially using 2D coordinates.

normal = {"x":-0.0065089149733523755,"y":-0.006280741243301691,"z":0}

This is where the problem comes in - my z component in the normal is 0 - when I use the normal to project the points to 2D space I inevitably end up with my four quad coordinates (multiplied by normal) to:

 normal D = {"x":-0.015987821599255592,"y":-0.009626234182414343,"z":0}
 normal A = {"x":-0.015987821599255592,"y":-0.009626234182414343,"z":0}
 normal B = {"x":-0.015517536142178694,"y":-0.010096519639491243,"z":0}
 normal C = {"x":-0.015517536142178694,"y":-0.010096519639491243,"z":0}

From above - D and A are duplicates, so is B and C -

This means that with this specific data - the duplicates would be removed, I'd end up with trying to triangulate a set of 2 vertices, namely:

{"x":-0.015987821599255592,"y":-0.009626234182414343,"z":0}
{"x":-0.015517536142178694,"y":-0.010096519639491243,"z":0}

Ending up in the zero result.

So I know why this is happening - but I don't see a solution.

Any pointers or advice welcome - This is essentially related to #67
