### ISSUE TITLE
client-side/Node environment

### ISSUE THREAD

**Issue by LFWill** [mapbox/earcut#69]
When using earcut on client-side I get the error: "module is undefined"

I suggest changing the first line from: 
```javascript
module.exports = earcut;
```

to:

```javascript
if ( 'undefined' !== typeof exports && 'undefined' !== typeof module ) {
    module.exports = earcut;
}
```

that way it should work normally on Node and on client-side.

**Comment by tmcw** [comment]
Browser builds are [available on the CDN](https://github.com/mapbox/earcut#install). We'd rather package this code automatically for a browser using browserify. You can download a standalone build from there, or include it in your project using browserify, webpack, or another browser bundler.

**Comment by LFWill** [comment]
Okay works for me, thanks!
