### ISSUE TITLE
There are some mistakes in test/test.js

### ISSUE THREAD

**Issue by finscn** [mapbox/earcut#76]
I just test one water-huge.json : 

The part of it : 

<img width="339" alt="2016-12-13 4 35 00" src="https://cloud.githubusercontent.com/assets/288367/21115677/696a1620-c0ed-11e6-8f0a-1888a0f8ebe8.png">
 
Some triangle  are out of polygon. 

<img width="117" alt="2016-12-13 4 35 57" src="https://cloud.githubusercontent.com/assets/288367/21115707/87dd7a3e-c0ed-11e6-9009-4828322ac1b7.png">

**Comment by finscn** [comment]
And If the algorithm has been changed (e.g. fix bug #74 ） , the expectedTriangles & expectedDeviation will be changed  too. 
So the current test case will not valid any more.

**Comment by mourner** [comment]
Earcut algorithm does not guarantee fully correct triangulation on self-intersecting geometries. This is stated in the readme.
