### ISSUE TITLE
Nitpick: use of "vertice" rather than "vertex"

### ISSUE THREAD

**Issue by hjfreyer** [mapbox/earcut#80]
While it's pretty clear that "vertice" is meant to be the singular of "vertices", it's not in the dictionary, and "vertex" may cause less confusion for those new to geometry. 

If that's the way you prefer it, though, feel free to close :)

**Comment by mourner** [comment]
Oh, you're totally right — thanks for noticing this! Want to submit a PR fixing the word across the repo?
