### ISSUE TITLE
Order of Nodes effects triangulation?

### ISSUE THREAD

**Issue by kpetrow** [mapbox/earcut#86]
Sorry if this is an obvious question but why does the node order effect the triangulation?  What order should points be in for best triangulation? 

```
 points = [30, 30, 200, 30, -30, 200, -30, 30, 200, -30, -30, 200];
 var triangles = earcut(points, null, 3);
 console.log(points); // [30, 30, 200, 30, -30, 200, -30, 30, 200, -30, -30, 200]
console.log(triangles); // [1, 0, 3]
```
 
Where as this order:
```
points = [30, 30, 200, -30, 30, 200, -30, -30, 200, 30, -30, 200];
var triangles = earcut(points, null, 3);
console.log(points); // [30, 30, 200, -30, 30, 200, -30, -30, 200, 30, -30, 200]
console.log(triangles); // [2, 3, 0, 0, 1, 2]

```

**Comment by mourner** [comment]
Unlike constrained Delaunay triangulation, the ear slicing triangulation results depend on the order of the vertices processed — this is normal. As long as the resulting triangles cover your input polygon, everything is working correctly.

**Comment by kpetrow** [comment]
What order gives proper results?  If you notice the above examples' results, one order for four points only gives one triangle.  That does not cover the bounds.  What is input polygon?  Link to manual/docs?

**Comment by kpetrow** [comment]
@mourner

**Comment by mourner** [comment]
@kpetrow can you show the visual output of triangulation in both cases?

**Comment by kpetrow** [comment]
@mourner Thanks for the help!
here is the code( I translated the one surface so you can see it on top):
```
bottomSurface = addSurface(  [30, 30, 200, -30, 30, 200, -30, -30, 200, 30, -30, 200] );
scene.add(bottomSurface) ;
bottomSurface = addSurface(  [30, 30, 204, 30, -30, 204, -30, 30, 204, -30, -30, 204] );
scene.add(bottomSurface) ;

function addSurface(points) {
    
    var triangles = earcut(points, null, 3);
    console.log('ponts:' + points);
    console.log('traingles' + triangles);

    var material = new THREE.MeshPhongMaterial({
        side: THREE.DoubleSide,
        wireframe: false,
        transparent: false,
        shininess: 100,
        shading: THREE.SmoothShading
    });
    if (triangles.length < 4)
        material = new THREE.MeshPhongMaterial({
            side: THREE.DoubleSide,
            wireframe: false,
            transparent: true,
            opacity: .5,
            color: 0xff0000,
            shininess: 100,
            shading: THREE.SmoothShading
        });
    //create a triangular geometry
    var geometry = new THREE.Geometry();
    for (var i = 0, j = points.length; i < j; i += 3) {
        geometry.vertices.push(new THREE.Vector3(points[i], points[i + 1], points[i + 2]));
    }
    for (var i = 0, j = triangles.length; i < j; i += 3) {
        var face = new THREE.Face3(triangles[i], triangles[i + 1], triangles[i + 2]);
        //add the face to the geometry's faces array
        geometry.faces.push(face);
    }
    //the face normals and vertex normals can be calculated automatically if not supplied above
    geometry.computeFaceNormals();
    geometry.computeVertexNormals();
    //console.log(geometry);
    return new THREE.Mesh(geometry, material);
}
```

console output(I could concieve of an issue in the THREE.js code, but clearly the earcut function gives a single triangle for 4 points in one order and 2 triangles for 4 points in another order):

> ponts: 30,30,200,       -30,30,200,          -30,-30,200,             30,-30,200
> traingles: 2,3,0    ,0,1,2
> ponts: 30,30,204,        30,-30,204 ,         -30,30,204,             -30,-30,204
> traingles: 1,0,3

And an image of what it looks like:
![image](https://user-images.githubusercontent.com/18248938/29079846-7e6d200a-7c1b-11e7-960c-9bf9eb9a9cc9.png)
