### ISSUE TITLE
Supporting different winding rules

### ISSUE THREAD

**Issue by bridger** [mapbox/earcut#95]
Is it feasible for earcut to support different winding rules? I'm working on a drawing app that can take user-drawn paths and fill them in. I'd like to use the non-zero winding rule.

These winding rules seem to mostly apply for self-intersecting paths, which may be out of scope for earcut. If so, no worries about closing this issue. I just thought I'd ask 😀

I really liked the API for earcut! It was easy to get up and running without any surprises.

**Comment by mourner** [comment]
Thanks! Yeah, handling self-intersections is out of scope for `earcut` — it was specifically optimized for valid, strictly simple polygons. A work is ongoing to create a lightweight JS polygon fixing library at github.com/mapbox/polysnap, and meanwhile there's a C++ solution at https://github.com/mapbox/wagyu
