### ISSUE TITLE
Polygons with valid but touching inner rings rendered with artifacts in mapbox-gl-js

### ISSUE THREAD

**Issue by bfrengley** [mapbox/earcut#98]
As described in https://github.com/mapbox/mapbox-gl-js/issues/6313.

Valid polygons which contain inner rings that touch at a single point (valid as per the OGC) render with triangular artifacts between points at certain zoom levels.

![37262187-7e696056-2606-11e8-9941-e1a875046b51](https://user-images.githubusercontent.com/37278140/37937909-2066a3ac-31b8-11e8-903f-8d9a77b9c214.png)

Relevant jsfiddle: https://jsfiddle.net/ndm00abw/20/ -- removing any of the polygons in this example removes the artifacts.

Suggested to be an issue with earcut by @mourner and @flippmoke

**Comment by mourner** [comment]
Reviewed this further and it looks like it's not an Earcut problem — what happens here is `geojson-vt` simplification for lower zoom levels introduces small self-intersections that cause artifacts like this. Let's keep the issue open in GL JS repo then.
